### ISSUE TITLE
Error in producing_event_script

### ISSUE THREAD

**Issue by pmerdrignac** [5gmetadmin/5gmeta-dev#3]
Hello all,

I have been playing with the exemples scripts these last days and have encountered an error for the production of events:

Traceback (most recent call last):
  File "kafka-even-sender_2.py", line 2, in <module>
    from confluent_kafka import SerializingProducer
ImportError: cannot import name 'SerializingProducer'

Any idea if I should use a specific version of confluen_kafka?

For information:
- System: Ubuntu 18.04
- Python 3.6.9

I thank you in advance.

Regards,
Pierre

**Comment by khaledchikh900** [comment]
pip show confluent-kafka | grep Version
Version: 2.0.2
Follow the guide in the documentation to install everything properly
